#!/bin/bash
set -a

: ${ONEAPI_SDK:="oneapi/eng-compiler/2024.07.30.002"}

#... load the necessary modules here ...
module reload
#module load ${ONEAPI_SDK}
#module load cmake
module load frameworks
module list
#...

#... set some environment variables
export CC=mpicc
export CXX=mpic++
export FC=mpif77
export NEKRS_HOME=/gila/Aurora_deployment/balin/Nek/nekRSv24/exe/nekrsv24_simai_frameworks

OCCA_CXX=icpx
OCCA_CXXFLAGS="-O3 -g -fdebug-info-for-profiling -gline-tables-only"
export SYCL_ROOT=${CMPROOT}/linux
#...

./build.sh -DCMAKE_INSTALL_PREFIX=$NEKRS_HOME
