#!/bin/bash
set -a

#... load the necessary modules here ...
module use /soft/modulefiles/
module load PrgEnv-gnu/8.5.0
module load gcc-native/12.3
module load spack-pe-base/0.8.0
module load cmake
module load python/3.10.13
module list
#...

#... set some environment variables
NEKRS_BUILD_DIR=$PWD
ENABLE_SMARTREDIS=ON
export NEKRS_HOME=/eagle/datascience/balin/Crux/Nek/exe/online_gnn
export CC=cc
export CXX=CC
export FC=ftn
OCCA_CXX=CC
OCCA_CXXFLAGS="-O3 -g -fdebug-info-for-profiling -gline-tables-only"
#...

#... build SmartRedis if enabled
if [ ${ENABLE_SMARTREDIS} == "ON" ]; then
  if [ -f "$NEKRS_HOME/SmartRedis/install/lib64/libsmartredis.so" ]; then
    echo -e "\033[35mFound SmartRedis at $NEKRS_HOME/SmartRedis/install/lib64/libsmartredis.so\033[m"
  else
    echo -e "\033[35mBuilding SmartRedis first ...\033[m"
    if [ ! -d "$NEKRS_HOME" ]; then
      mkdir -p $NEKRS_HOME
    fi
    cd $NEKRS_HOME
    git clone https://github.com/rickybalin/SmartRedis.git
    cd SmartRedis
    make lib DEP_CC=cc DEP_CXX=CC
    #pip install -e .
    cd $NEKRS_BUILD_DIR
    echo -e "\033[35mDone building SmartRedis\033[m"
    echo
  fi 
fi
#...

#... build nekRS
echo -e "\033[35mBuilding nekRS ...\033[m"
if [ ${ENABLE_SMARTREDIS} == "ON" ]; then
  ./build.sh \
  -DCMAKE_INSTALL_PREFIX=$NEKRS_HOME \
  -DENABLE_SMARTREDIS=ON -DSMARTREDIS_INSTALL_DIR=$NEKRS_HOME/SmartRedis/install \
  -DOCCA_ENABLE_CUDA=OFF \
  -DOCCA_ENABLE_HIP=OFF \
  -DOCCA_ENABLE_DPCPP=OFF \
  -DOCCA_ENABLE_OPENCL=OFF \
  -DENABLE_HYPRE_GPU=OFF \
  -DNEKRS_GPU_MPI=OFF \
  -DENABLE_ADIOS=OFF
else
  ./build.sh \
  -DCMAKE_INSTALL_PREFIX=$NEKRS_HOME \
  -DOCCA_ENABLE_CUDA=OFF \
  -DOCCA_ENABLE_HIP=OFF \
  -DOCCA_ENABLE_DPCPP=OFF \
  -DOCCA_ENABLE_OPENCL=OFF \
  -DENABLE_HYPRE_GPU=OFF \
  -DNEKRS_GPU_MPI=OFF \
  -DENABLE_ADIOS=OFF
fi
#...

