#!/bin/bash
set -a

SYSTEM="aurora"
DEPLOYMENT="colocated"
ML_TASK="inference"
NEKRS_HOME="/flare/Aurora_deployment/balin/Nek/nekRSv24/exe/nekrsv24_simai_frameworks"
VENV_PATH="/flare/Aurora_deployment/balin/Nek/nekRSv24/venv/_ssim_env/bin/activate"
PROJ_ID="Aurora_deployment"
QUEUE="lustre_scaling"

module load frameworks
source ${VENV_PATH}

script_name=ssimrun_${SYSTEM}
if [ ${DEPLOYMENT} == "colocated" ]; then
  NODES=`cat $PBS_NODEFILE | wc -l`
  NEKRS_HOME=$NEKRS_HOME \
  PROJ_ID=$PROJ_ID \
  QUEUE=$QUEUE \
  DEPLOYMENT=$DEPLOYMENT \
  ML_TASK=$ML_TASK \
  VENV_PATH=$VENV_PATH \
  ./${script_name} turbChannel $NODES 00:30
elif [ ${DEPLOYMENT} == "clustered" ]; then
  echo Work in progress
else
  echo Please select between clustered and colocated deployment of the workflow
fi

