#!/bin/bash
set -e

narg=1
if [ $1 == "hpc" ]; then
  narg=2
fi

if [ $# -ne $narg ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo "What manual page do you want?"
  echo "    par"
  echo "    env"
  echo "    hpc [frontier, aurora, polaris, perlmutter, all]"
  exit 1
fi

function extract_hpc_section() {
  local section_name="$1"
  local file="$2"

  awk -v target="$section_name" '
    BEGIN {
      found = 0
      target_lc = tolower(target);
      section = "";
    }
    /^[-]+$/ {
      getline;         # Read section name
      section = $0;
      section_lc = tolower($2);
      getline;         # Skip second dashed line
      if (section_lc == target_lc) {
        print "["section"]"
      }
      next;
    }
    section_lc == target_lc{
      print;
      found = 1;
    }
    END {
      if (!found) {
        print "hpcHelp.txt: HPC \"" target "\" not found.";
        exit(1)
      }
    }
  ' "$file"
}

case $1 in
  "par")
  cat $NEKRS_HOME/doc/parHelp.txt
  ;;
  "env")
  cat $NEKRS_HOME/doc/envHelp.txt
  ;;
  "hpc")
  if [ $2 == "all" ]; then
    cat $NEKRS_HOME/doc/hpcHelp.txt
  else
    extract_hpc_section $2 $NEKRS_HOME/doc/hpcHelp.txt
  fi
  ;;
esac

exit 0
